
defaults:
  containerRegistry: local
  tag: prod

services:
  proxy:
    additionalContent:
      build: ../../openslides-proxy/
  client:
    additionalContent:
      build: ../../openslides-client/
  backendAction:
    additionalContent:
      build: ../../openslides-backend/
  backendPresenter:
    additionalContent:
      build: ../../openslides-backend/
  backendManage:
    additionalContent:
      build: ../../openslides-backend/
    environment:
      OPENSLIDES_BACKEND_CREATE_INITIAL_DATA: 1
  datastoreReader:
    additionalContent: {
      build: {
        context: ../../openslides-datastore-service/,
        args: {
          MODULE: reader,
          PORT: 9010
        }
      }
    }
  datastoreWriter:
    additionalContent: {
      build: {
        context: ../../openslides-datastore-service/,
        args: {
          MODULE: writer,
          PORT: 9011
        }
      }
    }
  autoupdate:
    additionalContent:
      build: ../../openslides-autoupdate-service/
  auth:
    additionalContent:
      build: ../../openslides-auth-service/
  vote:
    additionalContent:
      build: ../../openslides-vote-service/
  media:
    additionalContent:
      build: ../../openslides-media-service/
  icc:
    additionalContent:
      build: ../../openslides-icc-service/
  projector:
    additionalContent:
      build: ../../openslides-projector-service/
  search:
    additionalContent:
      build: ../../openslides-search-service/
  manage:
    additionalContent:
      build: ../../openslides-manage-service/
