
defaults:
  containerRegistry: local
  tag: prod

services:
  # Datastore entries are a dirty fix, because manage tool still has it in compose template.
  # Please remove as soon as openslides-manage-service is removed 
  datastoreReader:
    containerRegistry: ghcr.io/openslides/openslides
    tag: latest
  datastoreWriter:
    containerRegistry: ghcr.io/openslides/openslides
    tag: latest
  proxy:
    additionalContent:
      build: ../../openslides-proxy/
  client:
    additionalContent:
      build: ../../openslides-client/
  backendAction:
    additionalContent:
      build: ../../openslides-backend/
  backendPresenter:
    additionalContent:
      build: ../../openslides-backend/
  backendManage:
    additionalContent:
      build: ../../openslides-backend/
    environment:
      OPENSLIDES_BACKEND_CREATE_INITIAL_DATA: 1
  autoupdate:
    additionalContent:
      build: ../../openslides-autoupdate-service/
  auth:
    additionalContent:
      build: ../../openslides-auth-service/
  vote:
    additionalContent:
      build: ../../openslides-vote-service/
  media:
    additionalContent:
      build: ../../openslides-media-service/
  icc:
    additionalContent:
      build: ../../openslides-icc-service/
  projector:
    additionalContent:
      build: ../../openslides-projector-service/
  search:
    additionalContent:
      build: ../../openslides-search-service/
  manage:
    additionalContent:
      build: ../../openslides-manage-service/
